export const links = {
  discord: "https://discord.com/invite/Zszgng9NdF",
  github: "https://github.com/mento-protocol",
  twitter: "https://twitter.com/MentoLabs",
  docs: "https://docs.mento.org/mento/mento-protocol/readme",
  mento2: "https://forum.celo.org/t/towards-mento-2-0/3473",
  gcp61: "https://celo.stake.id/#/proposal/62",
  app: "https://app.mento.org/",
  roadmap: "https://mento.canny.io/",
  forum: "https://forum.celo.org/c/mento/33",
  cookiePolicy: "/files/cookie-policy.pdf",
  mentoLabsTeam: "https://www.mentolabs.xyz/team",
  reserveSiteSource: "https://github.com/mento-protocol/reserve-site",
  privacy: "/legal/privacy",
  terms: "/legal/terms",
};
